/**
 * Signature database — built-in entries.
 *
 * Community-extensible: entries are plain data and may be merged at runtime by
 * `RouterSignatures.loadPack()` without shipping a new build (spec §4/§45).
 *
 * IMPORTANT: entries describe *identification* signals and documented
 * management endpoints only. Nothing in this file performs authentication
 * bypass, brute force or exploitation (spec §5/§22).
 *
 * © 2026 Mohamed Ibrahim Abu El-Ezz — All Rights Reserved.
 */

import type { RouterSignature, SignatureDatabaseMeta } from './types';

/** Huawei — GPON/ONT Home Gateways (HG8145, HG8245, EG8145, HN8145 ...). */
const huaweiHomeGateway: RouterSignature = {
  id: 'huawei.home-gateway',
  vendor: 'Huawei',
  model: 'Huawei Home Gateway (HG/EG series)',
  modelPatterns: ['(HG\\d{4}[A-Z0-9]*)', '(EG\\d{4}[A-Z0-9]*)', '(HN\\d{4}[A-Z0-9]*)', '(HG\\d{3}[A-Z0-9]*)'],
  aliases: ['Home Gateway', 'EchoLife', 'Echolife'],
  firmwarePatterns: [
    { pattern: 'V(\\d+R\\d{3})', label: 'firmware VxRy', extractGroup: 1, extractAs: 'firmware', weight: 0.2 },
  ],
  managementUrls: ['/', '/html/index.asp', '/asp/Login.asp', '/login.asp', '/cgi-bin/luci'],
  loginType: 'form-session-token',
  loginPath: '/asp/Login.asp',
  authMethod: 'rand-count + session (SessionID cookie)',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    wifi_channels: 'yes',
    guest_network: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    qos: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    firmware_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    restore: 'yes',
    logs: 'yes',
  },
  api: {
    deviceInfo: '/asp/GetRandCount.asp',
    deviceList: '/html/bbsp/common/GetLanUserDevInfo.asp',
    wifiInfo: '/html/bbsp/wlanbasic/WlanBasic.asp',
    wifiSet: '/html/bbsp/wlanbasic/WlanBasic.asp',
    wanInfo: '/html/bbsp/waninfo/WanInfo.asp',
    lanInfo: '/html/bbsp/lanconfig/LanConfig.asp',
    dhcpInfo: '/html/bbsp/lanconfig/LanConfig.asp',
    reboot: '/html/ssmp/deviceinfo/reboot.asp',
    backup: '/html/ssmp/configupload/configupload.asp',
  },
  operations: [
    {
      id: 'wifi.set_ssid',
      path: '/html/bbsp/wlanbasic/WlanBasic.asp',
      method: 'POST',
      encoding: 'form',
      staticBody: { x: 'InternetGatewayDevice.LANDevice.1.WLANConfiguration.{band}.SSID' },
      fieldMap: { ssid: 'InternetGatewayDevice.LANDevice.1.WLANConfiguration.{band}.SSID', band: 'band' },
      expect: { body: '(x=1|success|200)' },
      readBack: '/html/bbsp/wlanbasic/WlanBasic.asp',
      readBackPattern: 'SSID[^>]*>([^<]+)<',
      notes: 'TR-069 style WLAN path; band 1 = 2.4G, band 2 = 5G.',
    },
    {
      id: 'wifi.set_password',
      path: '/html/bbsp/wlanbasic/WlanBasic.asp',
      method: 'POST',
      encoding: 'form',
      staticBody: { x: 'InternetGatewayDevice.LANDevice.1.WLANConfiguration.{band}.PreSharedKey.1.PreSharedKey' },
      fieldMap: { password: 'InternetGatewayDevice.LANDevice.1.WLANConfiguration.{band}.PreSharedKey.1.PreSharedKey' },
      expect: { body: '(x=1|success)' },
      readBack: '/html/bbsp/wlanbasic/WlanBasic.asp',
      readBackPattern: 'PreSharedKey[^>]*>([^<]+)<',
    },
    {
      id: 'device.block',
      path: '/html/bbsp/common/setLanUserDevInfo.asp',
      method: 'POST',
      encoding: 'form',
      fieldMap: { mac: 'MacAddr', blocked: 'Enable' },
      staticBody: { x: 'InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.DeviceFilter' },
      expect: { body: '(success|200)' },
    },
    {
      id: 'router.reboot',
      path: '/html/ssmp/deviceinfo/reboot.asp',
      method: 'POST',
      encoding: 'form',
      staticBody: { x: 'InternetGatewayDevice.DeviceInfo.X_HW_Reboot' },
      expect: { body: '(success|200|x=1)' },
    },
  ],
  adapter: 'HuaweiAdapter',
  match: {
    titles: [
      { pattern: 'huawei\\s+(home\\s+)?gateway', weight: 0.42, label: 'title: Huawei Home Gateway' },
      { pattern: 'echolife', weight: 0.34, label: 'title: EchoLife' },
      { pattern: '^huawei$', weight: 0.3, label: 'title: Huawei' },
    ],
    headers: {
      server: [
        { pattern: 'huawei', weight: 0.24, label: 'header: Server: Huawei' },
        { pattern: 'HG\\d{4}', weight: 0.22, label: 'header: Server model code' },
      ],
    },
    body: [
      { pattern: 'getRandCount\\.asp', weight: 0.3, label: 'body: GetRandCount.asp' },
      { pattern: 'hw_login|hwframe|huawei\\.js', weight: 0.26, label: 'body: Huawei web framework' },
      { pattern: 'InternetGatewayDevice\\.LANDevice', weight: 0.28, label: 'body: TR-069 data model paths' },
      { pattern: 'hwont|ont/menu|ssmp/', weight: 0.2, label: 'body: ONT/SSMP management layout' },
    ],
    assets: [
      { pattern: 'hw(head|frame|common)|echolife', weight: 0.22, label: 'asset: Huawei framework JS/CSS' },
      { pattern: '\\.gch?', weight: 0.1, label: 'asset: .gch endpoint naming' },
    ],
    cookies: [
      { pattern: '^(SessionID|sessionid)$', weight: 0.14, label: 'cookie: SessionID' },
      { pattern: '^Cookie$', weight: 0.08, label: 'cookie: Cookie' },
      { pattern: '^language$', weight: 0.06, label: 'cookie: language' },
    ],
    formFields: [
      { pattern: 'Frm_Username|txt_Username|UserName', weight: 0.16, label: 'form: Huawei username field' },
      { pattern: 'Frm_Password|txt_Password', weight: 0.16, label: 'form: Huawei password field' },
    ],
    oui: ['104d77', '204a6f', '48ad08', '80b686', '9c28ef', 'e0247f', '744d28', '001882'],
    negative: [{ pattern: 'zyxel|arris|sagemcom|technicolor', weight: 0.2, label: 'competing ONT vendor token' }],
  },
  known: {
    blockedOperations: [],
    advisories: [
      'On Huawei ONTs, LAN-side device blocking is called "MAC filter" in most firmware builds.',
      'Some ISP-locked builds hide the 5 GHz basic page; the engine will report it as unsupported.',
    ],
  },
  uiSelectors: {
    deviceRow: 'table#userInfoTable tr, .deviceListItem',
    rebootButton: 'input[value*="Reboot"], input[value*="إعادة"]',
  },
  source: 'builtin',
  notes: 'Covers the ISP-issued Huawei ONT/Home Gateway family widely used by WE / Orange / Vodafone Egypt.',
};

/** Huawei HiLink consumer routers (WS5200, AX3, B5xx mobile Wi-Fi). */
const huaweiHilink: RouterSignature = {
  id: 'huawei.hilink',
  vendor: 'Huawei',
  model: 'Huawei HiLink Router',
  modelPatterns: ['(WS\\d{4})', '(AX\\d)', '(B\\d{3,4})'],
  managementUrls: ['/', '/api/webserver/SesTokInfo'],
  loginType: 'form-session-token',
  loginPath: '/html/index.html#/login',
  authMethod: 'SesTokInfo token + cookie session',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    guest_network: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    qos: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    logs: 'yes',
  },
  api: {
    deviceInfo: '/api/device/information',
    deviceList: '/api/lan/HostInfo',
    wifiInfo: '/api/wlan/status',
    wifiSet: '/api/wlan/basic-settings',
    wifiScan: '/api/wlan/neighbor',
    guestNetwork: '/api/wlan/guestnetwork',
    wanInfo: '/api/device/signal',
    stats: '/api/monitoring/traffic-statistics',
    reboot: '/api/device/control',
  },
  operations: [
    {
      id: 'router.reboot',
      path: '/api/device/control',
      method: 'POST',
      encoding: 'json',
      staticBody: { Control: '1' },
      expect: { body: 'OK' },
    },
    {
      id: 'wifi.set_ssid',
      path: '/api/wlan/basic-settings',
      method: 'POST',
      encoding: 'json',
      fieldMap: { ssid: 'WifiSsid', name: 'WifiSsid' },
      staticBody: { WifiBroadcast: '1' },
      expect: { body: 'OK' },
      readBack: '/api/wlan/status',
      readBackPattern: '"WifiSsid":"([^"]+)"',
    },
  ],
  adapter: 'HuaweiAdapter',
  match: {
    titles: [
      { pattern: 'hilink', weight: 0.36, label: 'title: HiLink' },
      { pattern: 'huawei\\s+router', weight: 0.34, label: 'title: Huawei Router' },
    ],
    apiPaths: [
      { pattern: 'SesTokInfo', weight: 0.34, label: 'api: /api/webserver/SesTokInfo' },
      { pattern: '/api/wlan/', weight: 0.22, label: 'api: HiLink wlan namespace' },
      { pattern: '/api/device/(information|control)', weight: 0.2, label: 'api: HiLink device namespace' },
    ],
    body: [
      { pattern: 'hilink|HiLinkApp', weight: 0.26, label: 'body: HiLink markers' },
      { pattern: '\\bWifiSsid\\b', weight: 0.16, label: 'body: WifiSsid JSON key' },
    ],
    cookies: [{ pattern: '^SessionID$', weight: 0.08, label: 'cookie: SessionID' }],
    headers: { server: [{ pattern: 'hilink', weight: 0.2, label: 'header: Server: HiLink' }] },
  },
  source: 'builtin',
};

/** TP-Link modern Archer UI (Tether / web UI 4-6, "luci"-style CGI). */
const tplinkArcher: RouterSignature = {
  id: 'tplink.archer',
  vendor: 'TP-Link',
  model: 'TP-Link Archer (web UI 4/5/6)',
  modelPatterns: ['(Archer\\s?[A-Z]\\d{3,4}[A-Z]*)', '(TL-[A-Z]\\d{3,4}[A-Z]*)', '(Deco [A-Z]\\d)'],
  aliases: ['Tether', 'TP-Link Router', 'Archer'],
  firmwarePatterns: [
    { pattern: '(\\d+\\.\\d+\\.\\d+\\s*Build\\s*\\d+)', label: 'firmware build string', extractGroup: 1, extractAs: 'firmware', weight: 0.22 },
  ],
  managementUrls: ['/', '/webpages/index.html', '/cgi-bin/luci'],
  loginType: 'form-session-token',
  loginPath: '/webpages/index.html',
  authMethod: 'JSON-RPC login, Base64(RSA-free MD5) password, stok token',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    device_rename: 'yes',
    device_details: 'yes',
    bandwidth_control: 'yes',
    per_device_stats: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    wifi_channels: 'yes',
    wifi_security_mode: 'yes',
    wifi_scan: 'yes',
    guest_network: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    qos: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    firmware_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    restore: 'yes',
    logs: 'yes',
  },
  api: {
    deviceInfo: '/cgi-bin/luci/;stok={stok}/admin/status?form=all',
    deviceList: '/cgi-bin/luci/;stok={stok}/admin/status?form=lan_host',
    deviceBlock: '/cgi-bin/luci/;stok={stok}/admin/access_control',
    wifiInfo: '/cgi-bin/luci/;stok={stok}/admin/wireless?form=wireless_2g',
    wifiSet: '/cgi-bin/luci/;stok={stok}/admin/wireless?form=wireless_2g',
    wifiScan: '/cgi-bin/luci/;stok={stok}/admin/wireless?form=wireless_survey',
    wanInfo: '/cgi-bin/luci/;stok={stok}/admin/status?form=wan',
    reboot: '/cgi-bin/luci/;stok={stok}/admin/system?form=reboot',
    backup: '/cgi-bin/luci/;stok={stok}/admin/firmware?form=config_backup',
  },
  operations: [
    {
      id: 'wifi.set_ssid',
      path: '/cgi-bin/luci/;stok={stok}/admin/wireless?form=wireless_2g',
      method: 'POST',
      encoding: 'json',
      staticBody: { method: 'set', 'wireless_2g': '{}' },
      fieldMap: { ssid: 'ssid', password: 'psk_key', channel: 'channel', security: 'security' },
      expect: { body: '"success"|\\"error_code\\":0' },
      readBack: '/cgi-bin/luci/;stok={stok}/admin/wireless?form=wireless_2g',
      readBackPattern: '"ssid":"([^"]*)"',
    },
    {
      id: 'wifi.set_password',
      path: '/cgi-bin/luci/;stok={stok}/admin/wireless?form=wireless_2g',
      method: 'POST',
      encoding: 'json',
      fieldMap: { password: 'psk_key' },
      expect: { body: '"success"|error_code\\":0' },
      readBack: '/cgi-bin/luci/;stok={stok}/admin/wireless?form=wireless_2g',
      readBackPattern: '"psk_key":"([^"]*)"',
    },
    {
      id: 'device.block',
      path: '/cgi-bin/luci/;stok={stok}/admin/access_control',
      method: 'POST',
      encoding: 'json',
      fieldMap: { mac: 'mac', blocked: 'enable' },
      staticBody: { method: 'set' },
      expect: { body: 'success|error_code\\":0' },
    },
    {
      id: 'router.reboot',
      path: '/cgi-bin/luci/;stok={stok}/admin/system?form=reboot',
      method: 'POST',
      encoding: 'json',
      staticBody: { method: 'set' },
      expect: { body: 'success' },
    },
  ],
  adapter: 'TPLinkAdapter',
  match: {
    titles: [
      { pattern: 'tp-?link', weight: 0.36, label: 'title: TP-Link' },
      { pattern: 'archer', weight: 0.3, label: 'title: Archer' },
    ],
    headers: {
      server: [
        { pattern: 'tp-?link', weight: 0.26, label: 'header: Server: TP-Link' },
        { pattern: 'Router\\s+Web\\s+Server', weight: 0.12, label: 'header: TP-Link web server' },
      ],
    },
    body: [
      { pattern: 'cgi-bin/luci', weight: 0.3, label: 'body: /cgi-bin/luci endpoint' },
      { pattern: 'stok|sysauth', weight: 0.22, label: 'body: stok/sysauth session markers' },
      { pattern: 'webpages/index\\.html|js/luci', weight: 0.2, label: 'body: TP-Link web UI 4/5 layout' },
      { pattern: 'encrypt_type|local_storage_key', weight: 0.18, label: 'body: TP-Link login bootstrap' },
    ],
    assets: [
      { pattern: 'luci|tplink', weight: 0.18, label: 'asset: TP-Link/LuCI bundle' },
      { pattern: 'webpages/', weight: 0.12, label: 'asset: /webpages/ bundle' },
    ],
    cookies: [
      { pattern: '^sysauth', weight: 0.22, label: 'cookie: sysauth' },
      { pattern: '^JSESSIONID$', weight: 0.08, label: 'cookie: JSESSIONID' },
    ],
    formFields: [{ pattern: 'pcp|encrypt_type|obfuscated', weight: 0.14, label: 'form: obfuscated password field' }],
    oui: ['14cc20', '3c46d8', '50c7bf', 'a42bb0', 'b09575', 'c46e1f', 'ec086b', 'f4f26d'],
    negative: [{ pattern: 'tenda|netcore|mercusys firmware copyright netcore', weight: 0.18, label: 'competing vendor token' }],
  },
  known: {
    advisories: [
      'TP-Link answers with `{"error_code":0}` on success; the verification engine reads the value back before reporting success.',
      'Older Archer firmware requires an AES-encrypted password (handled by TPLinkAdapter when advertised).',
    ],
  },
  uiSelectors: { deviceTable: 'table#lan_host_table tr', rebootButton: '#reboot_btn' },
  source: 'builtin',
};

/** TP-Link legacy web UI (WR/WA/TD series, HTTP Basic + /userRpm pages). */
const tplinkLegacy: RouterSignature = {
  id: 'tplink.legacy',
  vendor: 'TP-Link',
  model: 'TP-Link legacy router (WR/TD series)',
  modelPatterns: ['(TL-WR\\d{3,4}[A-Z]*)', '(TL-W\\d{3,4}[A-Z]*)', '(TL-MR\\d{3,4}[A-Z]*)', '(TD-W\\d{3,4}[A-Z]*)'],
  managementUrls: ['/', '/userRpm/LoginRpm.htm', '/userRpm/MenuRpm.htm'],
  loginType: 'http-basic',
  loginPath: '/userRpm/LoginRpm.htm',
  authMethod: 'HTTP Basic (realm carries the model name)',
  capabilities: {
    connected_devices: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_channels: 'yes',
    dhcp: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    traffic_stats: 'yes',
    firewall: 'yes',
    device_block: 'yes',
    wifi_5ghz: 'no',
  },
  api: {
    deviceList: '/userRpm/AssignedIpAddrListRpm.htm',
    wifiInfo: '/userRpm/WlanNetworkRpm.htm',
    wifiSet: '/userRpm/WlanNetworkRpm.htm',
    wanInfo: '/userRpm/StatusRpm.htm',
    dhcpInfo: '/userRpm/DhcpServerRpm.htm',
    reboot: '/userRpm/SysRebootRpm.htm',
  },
  operations: [
    {
      id: 'wifi.set_ssid',
      path: '/userRpm/WlanNetworkRpm.htm',
      method: 'POST',
      encoding: 'query',
      fieldMap: { ssid: 'ssid1', band: 'band' },
      staticBody: { Save: 'Save' },
      expect: { body: 'WlanNetworkRpm|success' },
      readBack: '/userRpm/WlanNetworkRpm.htm',
      readBackPattern: 'ssid1[^,]*,\\s*"([^"]+)"',
    },
    {
      id: 'router.reboot',
      path: '/userRpm/SysRebootRpm.htm?Reboot=Reboot',
      method: 'GET',
      encoding: 'none',
      expect: { body: 'reboot|Reboot' },
      notes: 'Device drops the connection immediately — success is asserted by the response, not a read-back.',
    },
  ],
  adapter: 'TPLinkAdapter',
  match: {
    authRealm: [
      { pattern: 'TP-?LINK\\s+Wireless\\s+Router\\s+(\\S+)', weight: 0.5, label: 'realm: TP-LINK Wireless Router <model>', extractGroup: 1, extractAs: 'model' },
      { pattern: 'TP-?LINK', weight: 0.36, label: 'realm: TP-LINK' },
    ],
    body: [
      { pattern: 'userRpm/', weight: 0.3, label: 'body: /userRpm/ legacy layout' },
      { pattern: 'javascript:\\s*window\\.location|save\\s*=\\s*"Save"', weight: 0.12, label: 'body: legacy TP-Link form' },
    ],
    headers: { server: [{ pattern: 'TP-LINK', weight: 0.2, label: 'header: Server: TP-LINK' }] },
    titles: [{ pattern: 'tp-?link', weight: 0.2, label: 'title: TP-Link' }],
    negative: [{ pattern: 'tplinkwebui', weight: 0.2, label: 'marker of the modern TP-Link UI' }],
  },
  source: 'builtin',
};

/** ZTE ZXHN ONT / home gateways. */
const zteZxhn: RouterSignature = {
  id: 'zte.zxhn',
  vendor: 'ZTE',
  model: 'ZTE ZXHN Gateway',
  modelPatterns: ['(ZXHN\\s?[A-Z]?\\d{3,4}[A-Z]*)', '(F\\d{3}[A-Z]*)', '(H\\d{3}[A-Z]*)'],
  firmwarePatterns: [
    { pattern: '(V\\d+\\.\\d+\\.\\d+[A-Za-z0-9.]*)', label: 'firmware version', extractGroup: 1, extractAs: 'firmware', weight: 0.2 },
  ],
  managementUrls: ['/', '/getpage.gch?pid=1002&nextpage=login_t.gch', '/cgi-bin/webproc', '/common_page/login.gch'],
  loginType: 'form-session-token',
  loginPath: '/getpage.gch?pid=1002&nextpage=login_t.gch',
  authMethod: 'Frm_Logintoken + sessionId cookie',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    wifi_channels: 'yes',
    guest_network: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    qos: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    restore: 'yes',
    logs: 'yes',
  },
  api: {
    deviceInfo: '/common_page/status_t.gch',
    deviceList: '/common_page/lan_hosts_t.gch',
    wifiInfo: '/common_page/wlan_basic_t.gch',
    wifiSet: '/common_page/wlan_basic_t.gch',
    wanInfo: '/common_page/wan_status_t.gch',
    reboot: '/common_page/reboot_t.gch',
  },
  operations: [
    {
      id: 'wifi.set_ssid',
      path: '/common_page/wlan_basic_t.gch',
      method: 'POST',
      encoding: 'form',
      fieldMap: { ssid: 'SSID1', band: 'band' },
      staticBody: { IF_ACTION: 'Apply' },
      expect: { body: 'IF_ACTION|success' },
      readBack: '/common_page/wlan_basic_t.gch',
      readBackPattern: 'name="SSID1"[^>]*value="([^"]*)"',
    },
    {
      id: 'wifi.set_password',
      path: '/common_page/wlan_security_t.gch',
      method: 'POST',
      encoding: 'form',
      fieldMap: { password: 'WPAKey' },
      staticBody: { IF_ACTION: 'Apply' },
      expect: { body: 'IF_ACTION|success' },
    },
    {
      id: 'router.reboot',
      path: '/common_page/reboot_t.gch',
      method: 'POST',
      encoding: 'form',
      staticBody: { IF_ACTION: 'Reboot' },
      expect: { body: 'Reboot' },
    },
  ],
  adapter: 'ZTEAdapter',
  match: {
    titles: [
      { pattern: 'zxhn', weight: 0.42, label: 'title: ZXHN' },
      { pattern: '^zte', weight: 0.34, label: 'title: ZTE' },
    ],
    body: [
      { pattern: 'getpage\\.gch', weight: 0.32, label: 'body: getpage.gch endpoints' },
      { pattern: 'Frm_Logintoken|Frm_Username|Frm_Password', weight: 0.28, label: 'body: ZTE login token form' },
      { pattern: '\\.gch\\?pid=', weight: 0.24, label: 'body: .gch?pid= routing' },
      { pattern: 'zxhn|ztecorp|zte\\.js', weight: 0.2, label: 'body: ZTE framework markers' },
    ],
    assets: [{ pattern: 'login_t\\.gch|mainframe|zte', weight: 0.2, label: 'asset: ZTE bundle' }],
    cookies: [
      { pattern: '^(sessionid|SessionId|SID)$', weight: 0.16, label: 'cookie: sessionId' },
      { pattern: '^_TEST_$', weight: 0.14, label: 'cookie: _TEST_ (ZTE)' },
      { pattern: '^stok$', weight: 0.12, label: 'cookie: stok' },
    ],
    formFields: [
      { pattern: 'Frm_Username|Frm_Logintoken', weight: 0.24, label: 'form: ZTE login fields' },
      { pattern: 'Frm_Password', weight: 0.2, label: 'form: ZTE password field' },
    ],
    authRealm: [{ pattern: 'ZXHN|ZTE', weight: 0.24, label: 'realm: ZTE' }],
    oui: ['044e5a', '344b50', '4c09b4', '5c3a3d', '9c2ea1', 'b075d5', 'd0154a', 'ec3eb3'],
    negative: [{ pattern: 'huawei|tp-link|dlink', weight: 0.16, label: 'competing vendor token' }],
  },
  known: {
    advisories: [
      'Some ZXHN builds (ISP-locked) expose read-only WLAN pages; the engine reports the write as unsupported rather than faking success.',
    ],
  },
  source: 'builtin',
};

/** D-Link DIR series. */
const dlinkDir: RouterSignature = {
  id: 'dlink.dir',
  vendor: 'D-Link',
  model: 'D-Link DIR Router',
  modelPatterns: ['(DIR-\\d{3,4}[A-Z]*)', '(DSL-\\d{3,4}[A-Z]*)', '(DWR-\\d{3,4}[A-Z]*)'],
  managementUrls: ['/', '/login.cgi', '/cgi-bin/webproc'],
  loginType: 'form-session-token',
  loginPath: '/login.cgi',
  authMethod: 'MD5(CHAP) password + uid cookie',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    wifi_channels: 'yes',
    guest_network: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    qos: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    logs: 'yes',
  },
  api: {
    deviceInfo: '/cgi-bin/webproc?getpage=html/index.html&var:menu=info',
    deviceList: '/cgi-bin/webproc?getpage=html/index.html&var:menu=status&var:page=client',
    wifiSet: '/cgi-bin/webproc?getpage=html/index.html&var:menu=wifi&var:page=wifi',
    reboot: '/cgi-bin/webproc?getpage=html/index.html&var:menu=system&var:page=reboot',
  },
  operations: [
    {
      id: 'wifi.set_ssid',
      path: '/cgi-bin/webproc',
      method: 'POST',
      encoding: 'form',
      fieldMap: { ssid: 'ssid', password: 'psk', channel: 'channel' },
      staticBody: { var: 'menu=wifi&page=wifi', act: 'save' },
      expect: { body: 'success|reboot' },
    },
    {
      id: 'router.reboot',
      path: '/cgi-bin/webproc',
      method: 'POST',
      encoding: 'form',
      staticBody: { var: 'menu=system&page=reboot', act: 'reboot' },
      expect: { body: 'reboot|success' },
    },
  ],
  adapter: 'DLinkAdapter',
  match: {
    titles: [
      { pattern: 'd-?link', weight: 0.38, label: 'title: D-Link' },
      { pattern: 'dir-\\d', weight: 0.3, label: 'title: DIR- model' },
    ],
    body: [
      { pattern: 'cgi-bin/webproc', weight: 0.28, label: 'body: /cgi-bin/webproc' },
      { pattern: 'dlink|D-Link\\.js', weight: 0.24, label: 'body: D-Link framework' },
      { pattern: 'login\\.cgi|getpage=html/index\\.html', weight: 0.22, label: 'body: D-Link login/webproc' },
      { pattern: 'html/\\w+/\\.\\./', weight: 0.1, label: 'body: D-Link multi-language resource path' },
    ],
    headers: { server: [{ pattern: 'd-?link|dlink', weight: 0.22, label: 'header: D-Link server' }] },
    cookies: [
      { pattern: '^uid$', weight: 0.18, label: 'cookie: uid' },
      { pattern: '^PRIVACY_LEVEL$', weight: 0.14, label: 'cookie: PRIVACY_LEVEL' },
    ],
    formFields: [{ pattern: 'ccp_username|log_pass|login\\.cgi', weight: 0.16, label: 'form: D-Link login fields' }],
    oui: ['001cf0', '0022b0', '1cbd0e', '28107b', '340804', '78542e', 'c8be19', 'f07d68'],
    negative: [{ pattern: 'routeros|mikrotik', weight: 0.2, label: 'competing vendor token' }],
  },
  source: 'builtin',
};

/** Tenda routers (AC/F-series, JSON goform API). */
const tenda: RouterSignature = {
  id: 'tenda.generic',
  vendor: 'Tenda',
  model: 'Tenda Router',
  modelPatterns: ['(AC\\d{3,4}[A-Z]*)', '(F\\d{2,3}[A-Z]*)', '(W\\d[0-9A-Z]*)'],
  managementUrls: ['/', '/login/Auth', '/goform/login'],
  loginType: 'form-session-token',
  loginPath: '/login.html',
  authMethod: 'JSON login with MD5 password → token cookie',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    device_rename: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_channels: 'yes',
    guest_network: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    qos: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    logs: 'yes',
  },
  api: {
    deviceInfo: '/goform/getSysInfo',
    deviceList: '/goform/getOnlineList',
    deviceBlock: '/goform/setBlackList',
    wifiInfo: '/goform/getWifiInfo',
    wifiSet: '/goform/setWifi',
    wanInfo: '/goform/getWanInfo',
    reboot: '/goform/setSysTools',
  },
  operations: [
    {
      id: 'wifi.set_ssid',
      path: '/goform/setWifi',
      method: 'POST',
      encoding: 'form',
      fieldMap: { ssid: 'ssid', password: 'wifiPwd', channel: 'channel' },
      staticBody: { module: 'wifi' },
      expect: { body: 'errCode\\s*[:=]\\s*0' },
      readBack: '/goform/getWifiInfo',
      readBackPattern: '"ssid"\\s*:\\s*"([^"]*)"',
    },
    {
      id: 'device.block',
      path: '/goform/setBlackList',
      method: 'POST',
      encoding: 'form',
      fieldMap: { mac: 'mac', blocked: 'enable' },
      expect: { body: 'errCode\\s*[:=]\\s*0' },
      readBack: '/goform/getBlackList',
      readBackPattern: '"mac"\\s*:\\s*"([^"]*)"',
    },
    {
      id: 'router.reboot',
      path: '/goform/setSysTools',
      method: 'POST',
      encoding: 'form',
      staticBody: { module: 'reboot' },
      expect: { body: 'errCode\\s*[:=]\\s*0' },
    },
  ],
  adapter: 'GenericRouterAdapter',
  match: {
    titles: [
      { pattern: 'tenda', weight: 0.38, label: 'title: Tenda' },
      { pattern: 'tenda\\s+router', weight: 0.42, label: 'title: Tenda Router' },
    ],
    body: [
      { pattern: 'goform/', weight: 0.24, label: 'body: /goform endpoints' },
      { pattern: 'tenda|tendaweb', weight: 0.26, label: 'body: Tenda framework markers' },
      { pattern: 'login/Auth|goform/getWifiInfo', weight: 0.2, label: 'body: Tenda API paths' },
    ],
    assets: [{ pattern: 'tenda', weight: 0.16, label: 'asset: Tenda bundle' }],
    cookies: [{ pattern: '^password$', weight: 0.16, label: 'cookie: password (Tenda session)' }],
    oui: ['00b00c', '049dd6', '08d833', '5cdd70', 'c83a35', 'd8320e'],
  },
  source: 'builtin',
};

/** Xiaomi MiWiFi. */
const xiaomiMiwifi: RouterSignature = {
  id: 'xiaomi.miwifi',
  vendor: 'Xiaomi',
  model: 'Xiaomi MiWiFi Router',
  modelPatterns: ['(R\\d{4}[A-Z]*)', '(AX\\d{4}[A-Z]*)', '(Mi Router [A-Z0-9]+)'],
  managementUrls: ['/', '/cgi-bin/luci/web', '/cgi-bin/luci/api/xqsystem/login'],
  loginType: 'form-session-token',
  loginPath: '/cgi-bin/luci/web',
  authMethod: 'POST /api/xqsystem/login (SHA1/MD5 password) → stok',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    device_rename: 'yes',
    bandwidth_control: 'yes',
    per_device_stats: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    wifi_channels: 'yes',
    guest_network: 'yes',
    qos: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    logs: 'yes',
  },
  api: {
    deviceInfo: '/cgi-bin/luci/;stok={stok}/api/misystem/sys_info',
    deviceList: '/cgi-bin/luci/;stok={stok}/api/misystem/devicelist',
    deviceBlock: '/cgi-bin/luci/;stok={stok}/api/misystem/set_macfilter',
    wifiInfo: '/cgi-bin/luci/;stok={stok}/api/xqnetwork/wifi_detail_all',
    wifiSet: '/cgi-bin/luci/;stok={stok}/api/xqnetwork/set_wifi',
    wifiScan: '/cgi-bin/luci/;stok={stok}/api/xqnetwork/wifi_survey',
    guestNetwork: '/cgi-bin/luci/;stok={stok}/api/xqnetwork/set_guestwifi',
    reboot: '/cgi-bin/luci/;stok={stok}/api/misystem/reboot',
    stats: '/cgi-bin/luci/;stok={stok}/api/misystem/status',
  },
  operations: [
    {
      id: 'device.block',
      path: '/cgi-bin/luci/;stok={stok}/api/misystem/set_macfilter',
      method: 'POST',
      encoding: 'json',
      fieldMap: { mac: 'mac', blocked: 'enable' },
      staticBody: { action: 'set' },
      expect: { body: '\\"code\\":0|\\"msg\\":\\"ok\\"' },
    },
    {
      id: 'router.reboot',
      path: '/cgi-bin/luci/;stok={stok}/api/misystem/reboot',
      method: 'POST',
      encoding: 'json',
      expect: { body: '\\"code\\":0' },
    },
  ],
  adapter: 'GenericRouterAdapter',
  match: {
    titles: [
      { pattern: '小米路由器|xiaomi|miwifi', weight: 0.4, label: 'title: Xiaomi MiWiFi' },
      { pattern: 'mi\\s?router', weight: 0.3, label: 'title: Mi Router' },
    ],
    body: [
      { pattern: 'xqsystem|misystem', weight: 0.34, label: 'body: xqsystem/misystem API namespace' },
      { pattern: 'miwifi|xiaomi', weight: 0.26, label: 'body: MiWiFi markers' },
      { pattern: '/cgi-bin/luci/;stok', weight: 0.2, label: 'body: stok session routing' },
    ],
    assets: [{ pattern: 'miwifi|xiaomi', weight: 0.16, label: 'asset: MiWiFi bundle' }],
    oui: ['009ec8', '286c07', '34ce00', '4c49e3', '64b473', '8cbebe', 'f0b429'],
  },
  source: 'builtin',
};

/** ASUS / ASUSWRT. */
const asusWrt: RouterSignature = {
  id: 'asus.asuswrt',
  vendor: 'ASUS',
  model: 'ASUS Wireless Router (ASUSWRT)',
  modelPatterns: ['(RT-[A-Z0-9]{1,6})', '(GT-[A-Z0-9]{1,6})', '(TUF-AX\\d+)', '(ZenWiFi [A-Z0-9]+)'],
  managementUrls: ['/', '/Main_Login.asp', '/login.cgi'],
  loginType: 'form-session-token',
  loginPath: '/Main_Login.asp',
  authMethod: 'login_authorization = Base64(user:pass) → asus_token cookie',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    device_rename: 'yes',
    bandwidth_control: 'yes',
    per_device_stats: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    wifi_channels: 'yes',
    wifi_scan: 'yes',
    guest_network: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    qos: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    firmware_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    restore: 'yes',
    logs: 'yes',
    vpn: 'yes',
    ddns: 'yes',
  },
  api: {
    deviceInfo: '/appGet.cgi?hook=sysinfo()',
    deviceList: '/appGet.cgi?hook=get_clientlist()',
    wifiInfo: '/appGet.cgi?hook=nvram_get(wl0_ssid)',
    wifiSet: '/applyapp.cgi',
    wifiScan: '/appGet.cgi?hook=get_wl_site_survey()',
    wanInfo: '/appGet.cgi?hook=wanlink_status()',
    stats: '/appGet.cgi?hook=get_netdev_client()',
    reboot: '/applyapp.cgi',
  },
  operations: [
    {
      id: 'device.block',
      path: '/applyapp.cgi',
      method: 'POST',
      encoding: 'form',
      fieldMap: { mac: 'mac', blocked: 'flag' },
      staticBody: { action_mode: 'apply', rc_service: 'restart_firewall' },
      expect: { body: 'Applying|success|(\\{\\})' },
    },
    {
      id: 'router.reboot',
      path: '/applyapp.cgi',
      method: 'POST',
      encoding: 'form',
      staticBody: { action_mode: 'reboot' },
      expect: { body: 'reboot|Applying' },
    },
  ],
  adapter: 'GenericRouterAdapter',
  match: {
    titles: [
      { pattern: 'asus\\s+wireless\\s+router', weight: 0.44, label: 'title: ASUS Wireless Router' },
      { pattern: 'asuswrt|asus router', weight: 0.34, label: 'title: ASUSWRT' },
    ],
    body: [
      { pattern: 'asus_token|login_authorization', weight: 0.32, label: 'body: ASUS login token fields' },
      { pattern: 'appGet\\.cgi|applyapp\\.cgi', weight: 0.3, label: 'body: ASUS appGet/applyapp endpoints' },
      { pattern: 'nvram_get|rc_service', weight: 0.22, label: 'body: ASUS NVRAM hooks' },
    ],
    headers: { server: [{ pattern: 'httpd/\\d|asuswrt', weight: 0.18, label: 'header: ASUS httpd' }] },
    cookies: [
      { pattern: '^asus_token$', weight: 0.28, label: 'cookie: asus_token' },
      { pattern: '^asus_token_s$', weight: 0.14, label: 'cookie: asus_token_s' },
    ],
    oui: ['002215', '08606e', '1c872c', '2c56dc', '38d547', '704d7b', 'ac9e17', 'f832e4'],
  },
  source: 'builtin',
};

/** MikroTik RouterOS (WebFig). */
const mikrotikRos: RouterSignature = {
  id: 'mikrotik.routeros',
  vendor: 'MikroTik',
  model: 'MikroTik RouterOS (WebFig)',
  modelPatterns: ['(RouterOS\\s*\\d+(\\.\\d+)*)', '(hEX|hAP|RB\\d+|CCR\\d+|CRS\\d+)'],
  managementUrls: ['/', '/webfig/', '/webfig/#System.0'],
  loginType: 'http-basic',
  loginPath: '/webfig/',
  authMethod: 'HTTP Basic / WebFig session (JSON .js proxy)',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    device_rename: 'yes',
    bandwidth_control: 'yes',
    per_device_stats: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    wifi_channels: 'yes',
    wifi_scan: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    qos: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    firmware_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    restore: 'yes',
    logs: 'yes',
    vpn: 'yes',
    ddns: 'yes',
    snmp: 'yes',
  },
  api: {
    deviceInfo: '/jsproxy/rest/system/resource',
    deviceList: '/jsproxy/rest/ip/dhcp-server/lease',
    wifiInfo: '/jsproxy/rest/interface/wireless',
    stats: '/jsproxy/rest/interface/monitor-traffic',
  },
  operations: [
    {
      id: 'router.reboot',
      path: '/jsproxy/rest/system/reboot',
      method: 'POST',
      encoding: 'json',
      expect: { body: '|\\{\\}' },
    },
  ],
  adapter: 'GenericRouterAdapter',
  match: {
    titles: [
      { pattern: 'routeros|webfig', weight: 0.44, label: 'title: RouterOS/WebFig' },
      { pattern: 'mikrotik', weight: 0.36, label: 'title: MikroTik' },
    ],
    body: [
      { pattern: 'jsproxy|\\.js?\\?\\d', weight: 0.26, label: 'body: RouterOS jsproxy' },
      { pattern: 'webfig|routeros', weight: 0.3, label: 'body: WebFig markers' },
      { pattern: 'sessionId|RouterOS', weight: 0.16, label: 'body: RouterOS session markers' },
    ],
    headers: { server: [{ pattern: 'mikrotik', weight: 0.3, label: 'header: Server: MikroTik' }] },
    oui: ['18fd74', '2cc81b', '48a98a', '64d154', '744d28', 'b869f4', 'cc2de0', 'e48d8c'],
    negative: [{ pattern: 'ubiquiti|airmax', weight: 0.18, label: 'competing vendor token' }],
  },
  source: 'builtin',
};

/** NETGEAR. */
const netgear: RouterSignature = {
  id: 'netgear.genie',
  vendor: 'NETGEAR',
  model: 'NETGEAR Router',
  modelPatterns: ['(R\\d{4,5}[A-Z]*)', '(Nighthawk [A-Z0-9 ]+)', '(D\\d{3,4}[A-Z]*)', '(RAX?\\d{2,3})'],
  managementUrls: ['/', '/start.htm', '/genie_login.cgi', '/login.cgi'],
  loginType: 'form-session-token',
  loginPath: '/start.htm',
  authMethod: 'token + MD5(password, token) form POST',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    device_rename: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    wifi_channels: 'yes',
    guest_network: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    qos: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    logs: 'yes',
  },
  api: {
    deviceInfo: '/cgi-bin/deviceinfo.cgi',
    deviceList: '/DEV_device.htm',
    wifiSet: '/wlg_adv.cgi',
    wanInfo: '/RST_status.htm',
    reboot: '/reboot.cgi',
  },
  operations: [
    {
      id: 'router.reboot',
      path: '/reboot.cgi',
      method: 'POST',
      encoding: 'form',
      staticBody: { 'reboot_type': 'Reboot' },
      expect: { body: 'reboot|success' },
    },
  ],
  adapter: 'GenericRouterAdapter',
  match: {
    titles: [
      { pattern: 'netgear', weight: 0.4, label: 'title: NETGEAR' },
      { pattern: 'nighthawk', weight: 0.32, label: 'title: Nighthawk' },
      { pattern: 'genie', weight: 0.24, label: 'title: NETGEAR genie' },
    ],
    body: [
      { pattern: 'genie_login|netgear', weight: 0.3, label: 'body: NETGEAR genie' },
      { pattern: 'deviceinfo\\.cgi|start\\.htm', weight: 0.22, label: 'body: NETGEAR CGI endpoints' },
      { pattern: 'netgear\\.js|ntgr', weight: 0.2, label: 'body: NETGEAR assets' },
    ],
    headers: { server: [{ pattern: 'netgear|genie', weight: 0.24, label: 'header: NETGEAR server' }] },
    cookies: [{ pattern: '^XSRF_TOKEN$', weight: 0.2, label: 'cookie: XSRF_TOKEN' }],
    oui: ['204e7f', '28c68e', '3c37d4', '4494fc', '6cb0ce', '9c3dcf', 'a00460', 'e091f5'],
  },
  source: 'builtin',
};

/** Linksys Smart Wi-Fi (JNAP). */
const linksysSmart: RouterSignature = {
  id: 'linksys.smartwifi',
  vendor: 'Linksys',
  model: 'Linksys Smart Wi-Fi Router',
  modelPatterns: ['(EA\\d{4,5})', '(MR\\d{4,5})', '(WRT\\d{4}[A-Z]*)', '(Velop [A-Z0-9]+)'],
  managementUrls: ['/', '/JNAP/'],
  loginType: 'vendor-custom',
  loginPath: '/',
  authMethod: 'JNAP POST (X-JNAP-Action header) + JNAP-TOKEN',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    device_rename: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    guest_network: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    logs: 'yes',
  },
  api: {
    deviceInfo: '/JNAP/ (http://linksys.com/jnap/core/GetDeviceInfo)',
    deviceList: '/JNAP/ (http://linksys.com/jnap/devicelist/GetDevices)',
    wanInfo: '/JNAP/ (http://linksys.com/jnap/router/GetWANStatus)',
    wifiInfo: '/JNAP/ (http://linksys.com/jnap/wirelessap/GetRadioInfo)',
  },
  adapter: 'GenericRouterAdapter',
  match: {
    titles: [{ pattern: 'linksys\\s+smart\\s+wi-?fi', weight: 0.44, label: 'title: Linksys Smart Wi-Fi' }],
    body: [
      { pattern: 'JNAP|jnap', weight: 0.36, label: 'body: JNAP protocol' },
      { pattern: 'X-JNAP-Action', weight: 0.3, label: 'body: X-JNAP-Action header usage' },
    ],
    headers: {
      server: [{ pattern: 'linksys', weight: 0.26, label: 'header: Linksys server' }],
      'x-jnap-action': [{ pattern: '.', weight: 0.3, label: 'header: X-JNAP-Action present' }],
    },
    oui: ['141fba', '30b5c2', '48f8b3', '58ef68', '94103e', 'c0c1c0'],
  },
  source: 'builtin',
};

/** Ubiquiti airOS / UniFi. */
const ubiquiti: RouterSignature = {
  id: 'ubiquiti.airos',
  vendor: 'Ubiquiti',
  model: 'Ubiquiti airOS / UniFi',
  modelPatterns: ['(AirOS\\s*\\S+)', '(NanoStation|PowerBeam|LiteBeam|UniFi [A-Z0-9 ]+)'],
  managementUrls: ['/', '/login.cgi', '/manage'],
  loginType: 'form-session-token',
  loginPath: '/login.cgi',
  authMethod: 'POST /api/login (UniFi) or /login.cgi (airOS)',
  capabilities: {
    connected_devices: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    wifi_channels: 'yes',
    wifi_scan: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    logs: 'yes',
  },
  api: {
    deviceInfo: '/status.cgi',
    deviceList: '/api/stat/sta',
    wifiInfo: '/api/s/default/rest/wlanconf',
    reboot: '/api/cmd/reboot',
  },
  adapter: 'GenericRouterAdapter',
  match: {
    titles: [
      { pattern: 'airos|ubiquiti', weight: 0.4, label: 'title: airOS/Ubiquiti' },
      { pattern: 'unifi', weight: 0.34, label: 'title: UniFi' },
    ],
    body: [
      { pattern: 'airos|ubnt', weight: 0.3, label: 'body: airOS markers' },
      { pattern: 'UniFi|unifi\\.js', weight: 0.26, label: 'body: UniFi markers' },
    ],
    headers: {
      server: [
        { pattern: 'airou?i?o?s|ubnt', weight: 0.3, label: 'header: Ubiquiti server' },
        { pattern: 'UniFi', weight: 0.24, label: 'header: UniFi server' },
      ],
    },
    oui: ['002722', '0418d6', '24a43c', '44d9e7', '68866f', '74acb9', 'dc9fdb', 'f09fc2'],
  },
  source: 'builtin',
};

/** OpenWrt / LuCI (extremely common on ISP-custom and community firmware). */
const openWrt: RouterSignature = {
  id: 'openwrt.luci',
  vendor: 'OpenWrt',
  model: 'OpenWrt / LuCI device',
  managementUrls: ['/', '/cgi-bin/luci', '/cgi-bin/luci/admin/status/overview'],
  loginType: 'form-session-token',
  loginPath: '/cgi-bin/luci',
  authMethod: 'luci_username/luci_password form → sysauth cookie',
  capabilities: {
    connected_devices: 'yes',
    device_block: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    wifi_5ghz: 'yes',
    wifi_channels: 'yes',
    wifi_scan: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    qos: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    traffic_stats: 'yes',
    backup: 'yes',
    restore: 'yes',
    logs: 'yes',
    snmp: 'yes',
  },
  api: {
    deviceInfo: '/cgi-bin/luci/admin/status/overview?status=1',
    deviceList: '/cgi-bin/luci/admin/network/dhcp?status=1',
    wifiInfo: '/cgi-bin/luci/admin/network/wireless?status=1',
    reboot: '/cgi-bin/luci/admin/system/reboot',
  },
  adapter: 'GenericRouterAdapter',
  match: {
    titles: [
      { pattern: 'openwrt|luci', weight: 0.4, label: 'title: OpenWrt/LuCI' },
      { pattern: 'immortalwrt', weight: 0.36, label: 'title: ImmortalWrt' },
    ],
    body: [
      { pattern: 'luci_username|luci_password', weight: 0.34, label: 'body: LuCI login fields' },
      { pattern: 'cgi-bin/luci', weight: 0.28, label: 'body: /cgi-bin/luci' },
      { pattern: 'openwrt|LuCI', weight: 0.24, label: 'body: OpenWrt markers' },
    ],
    cookies: [
      { pattern: '^sysauth', weight: 0.26, label: 'cookie: sysauth' },
      { pattern: '^luci_session$', weight: 0.2, label: 'cookie: luci_session' },
    ],
    negative: [{ pattern: 'tplinkwebui|tp-link', weight: 0.14, label: 'vendor UI on top of LuCI fork' }],
  },
  source: 'builtin',
};

/** Cisco small business / RV / consumer. */
const cisco: RouterSignature = {
  id: 'cisco.generic',
  vendor: 'Cisco',
  model: 'Cisco Router',
  modelPatterns: ['(RV\\d{3,4})', '(EA\\d{4})', '(Linksys E\\d+)', '(Cisco\\s+\\S+)'],
  managementUrls: ['/', '/login.html', '/cgi-bin/login'],
  loginType: 'form-session-token',
  loginPath: '/login.html',
  authMethod: 'session cookie + optional base64 password',
  capabilities: {
    connected_devices: 'yes',
    wifi: 'yes',
    wifi_ssid: 'yes',
    wifi_password: 'yes',
    dhcp: 'yes',
    dns: 'yes',
    firewall: 'yes',
    port_forwarding: 'yes',
    reboot: 'yes',
    wan_info: 'yes',
    lan_info: 'yes',
    logs: 'yes',
    backup: 'yes',
  },
  adapter: 'GenericRouterAdapter',
  match: {
    titles: [
      { pattern: 'cisco', weight: 0.36, label: 'title: Cisco' },
      { pattern: 'rv0?\\d{3}|rv\\d{3}', weight: 0.3, label: 'title: RV series' },
    ],
    headers: {
      server: [
        { pattern: 'cisco|Cisco-', weight: 0.3, label: 'header: Cisco server' },
        { pattern: 'lighttpd', weight: 0.06, label: 'header: lighttpd' },
      ],
    },
    body: [
      { pattern: 'cisco|rv042|rv320', weight: 0.26, label: 'body: Cisco markers' },
      { pattern: 'login\\.html|setup_wizard', weight: 0.12, label: 'body: Cisco login layout' },
    ],
    authRealm: [{ pattern: 'cisco', weight: 0.24, label: 'realm: Cisco' }],
    oui: ['000c29', '001a2f', '00259c', '1c6a7a', '68bdab', 'f4cfe2'],
  },
  source: 'builtin',
};

/** Generic fallback entry — always evaluated last, never overrides evidence. */
const genericFallback: RouterSignature = {
  id: 'generic.unknown',
  vendor: 'Unknown',
  model: 'Generic Router',
  managementUrls: ['/', '/login', '/index.html', '/admin/'],
  loginType: 'form-session',
  authMethod: 'auto-detected',
  adapter: 'GenericRouterAdapter',
  maxConfidence: 0.35,
  match: {},
  source: 'builtin',
  notes: 'Applied when nothing better matches. Only safe, read-oriented operations are attempted.',
};

export const BUILTIN_SIGNATURES: RouterSignature[] = [
  huaweiHomeGateway,
  huaweiHilink,
  tplinkArcher,
  tplinkLegacy,
  zteZxhn,
  dlinkDir,
  tenda,
  xiaomiMiwifi,
  asusWrt,
  mikrotikRos,
  netgear,
  linksysSmart,
  ubiquiti,
  openWrt,
  cisco,
  genericFallback,
];

export const BUILTIN_META: SignatureDatabaseMeta = {
  version: '2026.10.1',
  updatedAt: '2026-10-05T00:00:00.000Z',
  count: BUILTIN_SIGNATURES.length,
  vendors: [...new Set(BUILTIN_SIGNATURES.map((entry) => entry.vendor))],
};
